---
- name: Run Terraform
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Terraform init & apply
      community.general.terraform:
        project_path: "."
        backend_config:
          bucket: tf_state_bucket
          key: terraform.tfstate
          region: eu-north-1
        force_init: false
        force_apply: false
        lock: true
        lock_timeout: 600
        state: present

    - name: Get hosts from state file
      community.general.terraform_output:
        project_path: "."
      register: tf_info


- name: Install nginx on hosts from Terraform
  hosts: "{{ tf_info.hosts }}"
  become: true
  gather_facts: true

  tasks:
    - wait_for_connection:

    - setup:

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
