---
- name: Run Terraform
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Terraform init & apply
      cloud.terraform.terraform:
        project_path: "./"
        force_init: true
        state: present

    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory


- name: Install nginx on hosts from Terraform
  hosts: nginx
  connection: docker
  become: true
  gather_facts: true

  tasks:
    - wait_for_connection:

    - setup:

    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
