---
- name: Run Terraform
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Terraform init & apply
      community.general.terraform:
        project_path: "./"
        force_init: true
        state: present


- name: Install nginx on hosts from Terraform
  hosts: nginx
  become: true
  gather_facts: true

  tasks:
    - wait_for_connection:

    - setup:

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
